#if	!defined(SHARINGRESID_H_INCLUDE)
#define SHARINGRESID_H_INCLUDE

#define	SHARE_RESID_BASE				23000
// Menu
#define	SHARE_IDR_CONTEXTMENU			23001
// Dialog
#define SHARE_IDD_SHARE                 23001
#define SHARE_IDD_OPTIONS               23002
#define SHARE_IDD_SHAREOTHERS           23003
#define	SHARE_IDD_REMOTECONTROLDLG		23004
#define	SHARE_IDD_SHAPEFORMAT			23005
#define	SHARE_IDD_TEXT_FONT				23006
#define	SHARE_IDD_ANNOTATION			23007

#define	SHARE_IDS_FULLSCREENVIEW		23020
#define	SHARE_IDS_CAPTUREAUDIO			23021
#define	SHARE_IDS_STOPCAPTUREAUDIO		23022
#define	SHARE_IDS_STOPSHARING			23023
#define	SHARE_IDS_ENTERFS				23024
#define	SHARE_IDS_EXITFS				23025
#define SHARE_IDS_256COLOR              23026
#define SHARE_IDS_RICH256COLOR          23027
#define SHARE_IDS_16bit                 23028
#define SHARE_IDS_24bit                 23029
#define SHARE_IDS_SHAREOTHERS			23030
#define SHARE_IDS_SHAREMY				23031
#define SHARE_IDS_SNAME					23032
#define SHARE_IDS_MSGSHAREOTHER			23033
#define SHARE_IDS_MSGREJECT				23034
#define	SHARE_IDS_MSGREMOTESHARE		23035
#define	SHARE_IDS_GIVECONTROL			23036
#define	SHARE_IDS_GIVECONTROL2			23037
#define	SHARE_IDS_TAKEBACKCONTRLFROM	23038
#define	SHARE_IDS_PERMITCONTROL			23039
#define	SHARE_IDS_RELEASECONTROL		23040	
#define	SHARE_IDS_TAKEBACKCONTROL		23041
#define	SHARE_IDS_REQUESTCONTROL		23042
#define	SHARE_IDS_REQUESTCONTROLTIPS	23043
#define SHARE_IDS_TIPS_SHARING			23044
#define SHARE_IDS_TIPS_VIEWING			23045
#define SHARE_IDS_TIPS_FULLSCREEN		23046
#define SHARE_IDS_TIP_ERASER			23047
#define SHARE_IDS_TIP_LASER				23094
#define SHARE_IDS_TIP_HILIGHT			23095
#define SHARE_IDS_TIP_TEXT				23096
#define SHARE_IDS_TIP_MARK				23097
#define SHARE_IDS_TIP_CHECKMARK			23098
#define SHARE_IDS_TIP_XCHECKMARK		23099
#define SHARE_IDS_TIP_RIGHTPOINTER		23100
#define SHARE_IDS_TIP_LEFTPOINTER		23101
#define SHARE_IDS_TIP_UPPOINTER			23102
#define SHARE_IDS_TIP_DOWNPOINTER		23103
#define SHARE_IDS_TIP_DRAWING			23104
#define SHARE_IDS_TIP_PEN				23105
#define SHARE_IDS_TIP_RECTANGLE			23106
#define SHARE_IDS_TIP_FILLRECTANGLE		23107
#define SHARE_IDS_TIP_ROUNDRECTANGLE	23108
#define SHARE_IDS_TIP_FILLROUNDRECTANGLE	23109
#define SHARE_IDS_TIP_ELLIPSE			23110
#define SHARE_IDS_TIP_FILLELLIPSE		23111
#define SHARE_IDS_TIP_LINE				23112
#define SHARE_IDS_TIP_LINEARROW			23113
#define SHARE_IDS_TIP_LINEDOUBLEARROW	23114
#define SHARE_IDS_TIP_SELECT			23115
#define SHARE_IDS_TIP_PAGE				23116
#define SHARE_IDS_ENTERANNOT			23117
#define SHARE_IDS_LEAVEANNOT			23118
#define SHARE_IDS_TIP_LEAVEANNOT		23119
#define SHARE_IDS_CHECKMARK				23120
#define SHARE_IDS_XCHECKMARK			23121
#define SHARE_IDS_RPOINTER				23122
#define SHARE_IDS_LPOINTER				23123
#define SHARE_IDS_UPOINTER				23124
#define SHARE_IDS_DPOINTER				23125
#define SHARE_IDS_MATH					23126
#define SHARE_IDS_CHEM					23127
#define SHARE_IDS_PHONETIC				23128
#define SHARE_IDS_SYM					23128
#define SHARE_IDS_PICTURE				23129
#define SHARE_IDS_FREEHAND				23130
#define SHARE_IDS_RECT					23131
#define SHARE_IDS_FILLRECT				23132
#define SHARE_IDS_ROUNDRECT				23133
#define SHARE_IDS_FILLROUNDRECT			23134
#define SHARE_IDS_ELLIPSE				23135
#define SHARE_IDS_FILLELLIPSE			23136
#define SHARE_IDS_LINE					23137
#define SHARE_IDS_LINEARROW				23138
#define SHARE_IDS_LINEDARROW			23139
#define SHARE_IDS_DRAWINGFORMAT			23140
#define SHARE_IDS_SELECT				23141
#define SHARE_IDS_REMOVE				23142
#define SHARE_IDS_REMOVEALL				23143
#define SHARE_IDS_INFO					23144
#define SHARE_IDS_WHITEBOARD			23145
#define SHARE_IDS_PAGE					23146
#define SHARE_IDS_AUTOCOLOR				23147
#define SHARE_IDS_MORECOLOR				23148
#define	SHARE_IDS_MSGTITLE				23149
#define	SHARE_IDS_REMOVEMYALL			23150
#define SHARE_IDS_REMOVEOTHERS			23151
#define SHARE_IDS_CHANGEFONT			23152
#define SHARE_IDS_TAKEBACKANNOTFROMALL	23153
#define SHARE_IDS_PERMITANNOT			23154
#define SHARE_IDS_NOUSER				23155
#define SHARE_IDS_REMOTECONTROL			23156
#define SHARE_IDS_CONFIRMSETCONTROL		23157
#define SHARE_IDS_RELEASEANNOT			23158
#define SHARE_IDS_REQUESTANNOT			23159
#define SHARE_IDS_ANNOTATION			23160
#define SHARE_IDS_CONFIRMSETANNOT		23161
#define SHARE_IDS_REQUESTANNOTTIPS		23162
#define SHARE_IDS_WRONGBANDWIDTH		23163
#define SHARE_IDS_MORETHAN4CHANNELS		23164
#define SHARE_IDS_NOCONTROLTIPS			23165
#define SHARE_IDS_NOANNOTATETIPS		23166
#define SHARE_IDS_HASCONTROLTIPS		23167
#define SHARE_IDS_HASANNOTATETIPS		23168
#define SHARE_IDS_APPSHARING			23169
#define SHARE_IDS_DESKTOPSHARING		23170
#define SHARE_IDS_NOAPPSELECTED			23171

#define SHARE_IDB_TOOLBAR               203

#define SHARE_IDC_SHAREREGION           201
#define SHARE_IDC_SHAREDESKTOP          202
#define SHARE_IDC_RUNNINGAPPLICATION    203
#define SHARE_IDC_LAUNAPPLICATION       204
#define SHARE_IDC_LISTALLAPP            206
#define SHARE_IDC_STOP                  207
#define SHARE_IDC_START                 208
#define SHARE_IDC_RUNNINGAPP            209
#define SHARE_IDC_DEFAULT               210
#define SHARE_IDC_BANDWIDTH             211
#define SHARE_IDC_COLORDEPTH            212
#define SHARE_IDC_FRAMERATE             213
#define SHARE_IDC_SELECTSTATIC			215
#define SHARE_IDC_OPTIONS               216
#define SHARE_IDC_USERS                 214
#define SHARE_IDC_SHAREDUSER            217
#define SHARE_IDC_STATIC_OTHER          219
#define SHARE_IDC_STATIC_OTHER2         220
#define SHARE_IDC_USERLIST				221
#define SHARE_IDC_FONTBAR				222
#define SHARE_IDC_FONTFLAG				223
#define SHARE_IDC_LASERPOINTER			224
#define SHARE_IDC_HILIGHT				225
#define SHARE_IDC_PEN					226
#define SHARE_IDC_XCHECK				227
#define SHARE_IDC_CHECK					228
#define SHARE_IDC_RIGHTPOINTER			229
#define SHARE_IDC_LEFTPOINTER			230
#define SHARE_IDC_UPPOINTER				231
#define SHARE_IDC_DOWNPOINTER			232
#define SHARE_IDC_SELECT				233
#define SHARE_IDC_REMOVE				234
#define SHARE_IDC_LASERPOINTEX			235

#define SHARE_BUTTON_NORMAL				236
#define SHARE_BUTTON_HILIGHT			237

#define	SHARE_IDC_FILLCOLOR				238
#define	SHARE_IDC_PENCOLOR				239
#define	SHARE_IDC_WEIGHT				240
#define	SHARE_IDC_PENWEIGHT_LIST		241
#define	SHARE_IDC_PENWEIGHT				242
#define	SHARE_IDC_PENSTYLE				243
#define	SHARE_IDC_TYPEFACE				244
#define	SHARE_IDC_POINTSIZE				245
#define	SHARE_IDC_CHARSET				246
#define	SHARE_IDC_USERNAME				248
#define	SHARE_IDC_SEARCH				249

#define	SHARE_IDC_ICON					250

// Private
#define	SHARE_IDM_EDIT_CUT					200
#define	SHARE_IDM_EDIT_COPY					201
#define	SHARE_IDM_EDIT_PASTE				202
#define	SHARE_IDM_EDIT_SELECTALL			203

#define SHARING_IDM_HIGHLIGHT				21768
#define SHARING_IDM_TEXT					21769
#define SHARING_IDM_MARK					21770
#define SHARING_IDM_SYM						21771	
#define SHARING_IDM_DRAWING					21772
#define SHARING_IDM_SELECT					21773
#define SHARING_IDM_FUNCTION				21774

#define SHARING_IDM_BASE					21800

#define SHARING_IDM_MARK_CHECKMARK			SHARING_IDM_BASE+1
#define SHARING_IDM_MARK_XCHECKMARK			SHARING_IDM_BASE+2
#define SHARING_IDM_MARK_RIGHTPOINTER		SHARING_IDM_BASE+3	
#define SHARING_IDM_MARK_LEFTPOINTER		SHARING_IDM_BASE+4
#define SHARING_IDM_MARK_UPPOINTER			SHARING_IDM_BASE+5
#define SHARING_IDM_MARK_DOWNPOINTER		SHARING_IDM_BASE+6

#define SHARING_IDM_MARK_SYM_MATH			SHARING_IDM_BASE+9
#define SHARING_IDM_MARK_SYM_CHEM			SHARING_IDM_BASE+10
#define SHARING_IDM_MARK_SYM_PHONETIC		SHARING_IDM_BASE+11
#define SHARING_IDM_MARK_SYM_OTHERS			SHARING_IDM_BASE+12
#define SHARING_IDM_MARK_SYM_PICTURE		SHARING_IDM_BASE+13

#define SHARING_IDM_DRAWING_FORMAT			SHARING_IDM_BASE+15
#define SHARING_IDM_DRAWING_FREEHAND		SHARING_IDM_BASE+16
#define SHARING_IDM_DRAWING_RECTANGLE		SHARING_IDM_BASE+17
#define SHARING_IDM_DRAWING_FILLRECTANGLE	SHARING_IDM_BASE+18
#define SHARING_IDM_DRAWING_ROUNDRECTANGLE	SHARING_IDM_BASE+19
#define SHARING_IDM_DRAWING_FILLROUNDRECTANGLE	SHARING_IDM_BASE+20
#define SHARING_IDM_DRAWING_ELLIPSE			SHARING_IDM_BASE+21
#define SHARING_IDM_DRAWING_FILLELLIPSE		SHARING_IDM_BASE+22	
#define SHARING_IDM_DRAWING_LINE			SHARING_IDM_BASE+23
#define SHARING_IDM_DRAWING_LINEARROW		SHARING_IDM_BASE+24
#define SHARING_IDM_DRAWING_LINEDOUBLEARROW	SHARING_IDM_BASE+25	

#define SHARING_IDM_SELECT_SELECT			SHARING_IDM_BASE+29
#define SHARING_IDM_SELECT_ERASER			SHARING_IDM_BASE+30
#define SHARING_IDM_SELECT_ERASERALL		SHARING_IDM_BASE+31
#define SHARING_IDM_SELECT_ERASERMYALL		SHARING_IDM_BASE+32
#define SHARING_IDM_SELECT_ERASEROTHERS		SHARING_IDM_BASE+33
#define SHARING_IDM_CHANGEFONT				SHARING_IDM_BASE+34

#define	SHARING_IDM_NOTHANDLEDID1			SHARING_IDM_BASE+36
#define	SHARING_IDM_NOTHANDLEDID2			SHARING_IDM_BASE+37
#define	SHARING_IDM_NOTHANDLEDID3			SHARING_IDM_BASE+38
#define	SHARING_IDM_NOTHANDLEDID4			SHARING_IDM_BASE+39
#define	SHARING_IDM_NOTHANDLEDID5			SHARING_IDM_BASE+40
#define	SHARING_IDM_NOTHANDLEDID6			SHARING_IDM_BASE+41
#define	SHARING_IDM_NOTHANDLEDID7			SHARING_IDM_BASE+42
#define	SHARING_IDM_NOTHANDLEDID8			SHARING_IDM_BASE+43

#define	SHARING_IDM_CAPTUREAUDIO			SHARING_IDM_BASE+50	
#define	SHARING_IDM_STOPCAPTUREAUDIO		SHARING_IDM_BASE+51	
#define	SHARING_IDM_STOPSHARING				SHARING_IDM_BASE+52
#define	SHARING_IDM_PAUSESHARING			SHARING_IDM_BASE+53
#define	SHARING_IDM_CONTINUESHARING			SHARING_IDM_BASE+54
#define	SHARING_IDM_STOPFS					SHARING_IDM_BASE+55

#define	SHARING_IDM_TAKEBACKCONTROL			SHARING_IDM_BASE+56
#define	SHARING_IDM_GIVECONTROL				SHARING_IDM_BASE+57
#define	SHARING_IDM_SETCONTROLLERDLG		SHARING_IDM_BASE+58
#define	SHARING_IDM_RELEASECONTROL			SHARING_IDM_BASE+59
#define	SHARING_IDM_REQUESTCONTROL			SHARING_IDM_BASE+60
#define	SHARING_IDM_ENTERANNOT				SHARING_IDM_BASE+61
#define	SHARING_IDM_LEAVEANNOT				SHARING_IDM_BASE+62
#define	SHARING_IDM_SETANNOTUSERDLG			SHARING_IDM_BASE+63
#define	SHARING_IDM_TAKEBACKANNOTFROMALL	SHARING_IDM_BASE+64
#define	SHARING_IDM_RELEASEANNOT			SHARING_IDM_BASE+65
#define	SHARING_IDM_REQUESTANNOT			SHARING_IDM_BASE+66
#define	CMR_IDM_VIEW_FULLSCREEN2			SHARING_IDM_BASE+67

#define	SHARING_IDM_SWITCHTO_DOCSHARING		SHARING_IDM_BASE+68
#define	SHARING_IDM_SWITCHTO_WHITEBOARD		SHARING_IDM_BASE+69

#define	SHARING_IDM_MIN1					SHARING_IDM_BASE+76
#define	SHARING_IDM_MAX1					SHARING_IDM_BASE+360

#define	SHARING_IDM_MIN2					SHARING_IDM_BASE+361
#define	SHARING_IDM_MAX2					SHARING_IDM_BASE+661

#define SHARING_IDM_REQUEST_CONTROL			SHARING_IDM_BASE+80
#define SHARING_IDM_REQUEST_ANNOTATION		SHARING_IDM_BASE+81
#define SHARING_IDM_RETURN_STD_VIEW			SHARING_IDM_BASE+82
#define SHARING_IDM_QUIT_TRAIN				SHARING_IDM_BASE+83
#define SHARING_IDM_QUIT_SHARING			SHARING_IDM_BASE+84
#endif
	